### ISSUE TITLE
PlantUML tree example syntax change

### ISSUE THREAD

**Issue by korhadris** [terrastruct/text-to-diagram-site#21]
For the PlantUML tree example, the syntax should be changed from `->` to `-->`. It drastically changes how it is rendered, and will actually look like a tree with the change.

**Comment by alixander** [comment]
Tree is better! 

I tried using this for some other diagrams, but didn't find it uniformly better. It's unclear to me when to use this extra hyphen.

For example, with another hyphen, I get this.

<img width="541" alt="Screen Shot 2022-12-19 at 11 54 13 AM" src="https://user-images.githubusercontent.com/3120367/208508887-5af4da86-01be-4e84-9bcb-1a0dcf5e60ca.png">

Currently, without the extra hyphen, it's this:

<img width="555" alt="Screen Shot 2022-12-19 at 11 54 23 AM" src="https://user-images.githubusercontent.com/3120367/208508959-f6a47c31-807b-4887-b1e6-51649263d26d.png">

I kind of prefer the old version
