### ISSUE TITLE
[Question] PlantUML images from any URL?

### ISSUE THREAD

**Issue by Potherca** [terrastruct/text-to-diagram-site#46]
I was curious regarding two statements regarding PlantUML and images/icon:

> Icons: Icons and images are essential to professional-looking diagrams. How do the different tools handle it? Note: PlantUML's icon system is to include pre-packaged icon sets, so the example shown is one that uses their icon set.

and 

> |  Features | PlantUML |
> | --- | :-: |
>  | Images & Icons: What are the available options for including images and icons | X |

As far as I'm aware, in PlantUML, an icon or image can be loaded from any URL. At least, I've not had any issues thus far.
Am I missing something, or am I reading the content wrong?

**Comment by alixander** [comment]
> PlantUML, an icon or image can be loaded from any URL

do you have an example? I must've missed it, I was looking at https://plantuml.com/stdlib

**Comment by Potherca** [comment]
Sure! 


For instance, using the example from the [gilbarbara-plantuml-sprites](https://github.com/plantuml-stdlib/gilbarbara-plantuml-sprites) repo:

```plantuml
@startuml
!$SPRITESURL = 'https://raw.githubusercontent.com/plantuml-stdlib/gilbarbara-plantuml-sprites/v1.0/sprites'
!include $SPRITESURL/flask.puml
!include $SPRITESURL/kafka.puml
!include $SPRITESURL/kotlin.puml
!include $SPRITESURL/cassandra.puml

rectangle "<$flask>\nwebapp" as webapp
queue "<$kafka>" as kafka
rectangle "<$kotlin>\ndaemon" as daemon
database "<$cassandra>" as cassandra

webapp -> kafka
kafka -> daemon
daemon --> cassandra
@enduml
```

![](http://cdn-0.plantuml.com/plantuml/png/VL31IWCn4BtdAwQbqDFkwbMq5454y22jthpCxawtORD9p4oidszCIgiWXP3CvBrvxoLh5WmI9wDcY-tBvkdrOVksUOOxMEv5FDyqJS13FMZPnpOoXSvP8IjrvwR66xG_enLBRtJR3Dgq6DB2wWpve8Mu-RokhvfZirGpRJiJUu9VditE88-rprd-mqVSZNW9TsAqlK3ea1bj7x1mb6Wn18_Qm7s9lMGmRd0Cz8MJDwGKZzhwX4mmEUkwVN0JWOIOe42Te1qCmVnsaREltks1MlH-3iXGIlKHAMPAZh_AK2x_2fJmIQ57IbQPLahLes2Bd6cd9nIXKwjKiODgTLJFUsfFAlc0AjsSfzPa-_GLtm00)

All "[sprites](https://plantuml.com/sprite)" are loaded from remote files. Sprites are a converted form of image, but the same can be done using images:

```plantuml
@startuml
!$IMAGEURL = 'https://raw.githubusercontent.com/plantuml-stdlib/gilbarbara-plantuml-sprites/master/pngs'

rectangle "<img:$IMAGEURL/flask.png>\nwebapp" as webapp
queue "<img:$IMAGEURL/kafka-icon.png>" as kafka
rectangle "<img:$IMAGEURL/kotlin.png>\ndaemon" as daemon
database "<img:$IMAGEURL/cassandra.png>" as cassandra

webapp -> kafka
kafka -> daemon
daemon --> cassandra
@enduml
```

![](http://cdn-0.plantuml.com/plantuml/png/VOv1ImCn48Nl-HLZ4NhQvbwqL46Ae1V1cvVPtUasR3A9cGdrvnjtI_TG448oUOzltjkBOjOIlBcxVtr_EhnyVhp18wnFgacsrcOyRmQdfz8MeTn5LcBTT37Ov97_m4QqzwwrW_CjvdgmMQoKdPBOWAAKRU91riQeKqzmS1wUPs0juECG1UW7G_9aZ8oEKtK2XCYnE-KO23INQcNg57dm1Ai75uRjjROzUfHnKqDsNtoc5bDQ0GhCe_akL6wP4OyZDgwBF84JC6d_v8nHlUDBK8zKAqxSF9eU5LkKMwv34UG-un9rbOoPQqApk-HFT_rUrquFD5LPg3rnNuB_1G00)

**Comment by alixander** [comment]
@Potherca Right but that's a pre-package icon set. 

Can it for example use your profile pic?

<img width="264" alt="Screen Shot 2023-04-17 at 1 56 31 PM" src="https://user-images.githubusercontent.com/3120367/232608970-1caadd85-bca4-4087-90c2-a27b74a7bb59.png">

https://play.d2lang.com/?script=qlDQtVOo5KrUA4WclUJGSUlBsZW-fmJZYkliUbFeemZJRmlSaXFqUXJ-XklqXolecn6ufqm-oaWpuam5fbGthYFama0JFyAAAP__&

**Comment by Potherca** [comment]
Ah, I think I am beginning to understand... From the perspective of PlantUML "prepackaged" means it is part of the `jar` and can be used by `!include <whatever>` instead of being an external (or local) URL `!include ...`. But it doesn't distinguish the need to make a "sprite" from an image (to be used as an icon) as "packaged".

I think the different concepts in PlantUML (Image, Sprite, Icon) are also slightly skewed and confused. Especially because you can _also_ use [`<&icon>`](https://plantuml.com/openiconic) but only from a predefined list which (as far as I can see) can't even be extended. Then again, I've also never really seen that used in the wild (everybody uses "sprites" instead).

From my perspective, PlantUML is a great tool for all it can do, but I'm _very_ hesitant in suggesting it to new users.
Especially as it has consistently shown to be confusing and inconsistent. :disappointed: 

The PlantUML equivalent of the above _could_ be

```plantuml
@startuml
rectangle "<img:https://avatars.githubusercontent.com/u/195757?s=80&v=4>" as y

[x] --> y
@enduml
```
![](http://cdn-0.plantuml.com/plantuml/png/SoWkIImgAStDuIfAJIv9p4lFILLGiidCJRVAA2afABRIrqyiImGgATPBpop9A4qgBKujIixFAqdDAz5Bpi_LBzKtj3GrDpMtBxQrC50hipMnKr98B5QevEAAheXLqDMr0p8TKlDIW3O00000)

but then the question would be if that constitutes an "icon"... :thinking:

**Comment by alixander** [comment]
> "prepackaged" means it is part of the jar

yeah that's a reasonable definition -- i'll change it to just "packaged".

> The PlantUML equivalent of the above could be

oh, that totally counts, I'll make the change that says PlantUML can load from any URL too.
