### ISSUE TITLE
add pricing

### ISSUE THREAD

**Issue by newprogrammers01** [terrastruct/text-to-diagram-site#55]
add  price of terrastruct cloud (https://terrastruct.com/#pricing)

> Terrastruct Bundle $20 month/user
> Enterprise $30 month/user

***vs***

mermaid cloud (https://www.mermaidchart.com/):
> FREE $0  free forever
> PRO $6.67 / month billed annually ($80) per team member
> ENTERPRISE $17 / month billed annually ($204) per team member

**Comment by alixander** [comment]
The website isn't about comparing services, just the language.
